name: Plugin Check

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  plugin-check-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: WordPress/plugin-check-action@v1
      with:
        build-dir: '.'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        slug: "awdev-plugins-updater"
        wp-version: latest
        strict: true
        exclude: |
          .github/
          tests/
          vendor/
          composer.json
          composer.lock
          phpunit.xml
          .distignore
  plugin-check-trunk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: WordPress/plugin-check-action@v1
      with:
        build-dir: '.'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        slug: "awdev-plugins-updater"
        wp-version: trunk
        include-experimental: true
        strict: true
        exclude: |
          .github/
          tests/
          vendor/
          composer.json
          composer.lock
          phpunit.xml
          .distignore
