name: Plugin Check

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  plugin-check-latest:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v6
    - name: Prepare clean plugin directory
      run: |
        mkdir ../plugin-clean
        rsync -av --exclude='.git' \
                  --exclude='.github' \
                  --exclude='tests' \
                  --exclude='vendor' \
                  --exclude='composer.json' \
                  --exclude='composer.lock' \
                  --exclude='phpunit.xml' \
                  --exclude='.distignore' \
                  --exclude='*.md' \
                  --exclude='readme-de.txt' \
                  --exclude='CHANGELOG.txt' \
                  --exclude='CHANGELOG-de.txt' \
                  ./ ../plugin-clean/
    - uses: WordPress/plugin-check-action@v1
      with:
        build-dir: '../plugin-clean'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        slug: "awdev-plugins-updater"
        
  plugin-check-trunk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v6
    - name: Prepare clean plugin directory
      run: |
        mkdir ../plugin-clean
        rsync -av --exclude='.git' \
                  --exclude='.github' \
                  --exclude='tests' \
                  --exclude='vendor' \
                  --exclude='composer.json' \
                  --exclude='composer.lock' \
                  --exclude='phpunit.xml' \
                  --exclude='.distignore' \
                  --exclude='*.md' \
                  --exclude='readme-de.txt' \
                  --exclude='CHANGELOG.txt' \
                  --exclude='CHANGELOG-de.txt' \
                  ./ ../plugin-clean/
    - uses: WordPress/plugin-check-action@v1
      with:
        build-dir: '../plugin-clean'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        slug: "awdev-plugins-updater"
